// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using Violation_p2.Models;

#nullable disable

namespace Violation_p2.Migrations
{
    [DbContext(typeof(ModelContext))]
    [Migration("20231018114811_add4")]
    partial class add4
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Violation_p2.Models.Aboutu", b =>
                {
                    b.Property<int>("AboutuId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutuId"));

                    b.Property<string>("Content")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Imagepath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Pargraph")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("AboutuId");

                    b.ToTable("Aboutus");
                });

            modelBuilder.Entity("Violation_p2.Models.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<string>("Content")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Imagepath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("PublishDate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("Userid")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("BlogId");

                    b.HasIndex("Userid");

                    b.ToTable("Blogs");
                });

            modelBuilder.Entity("Violation_p2.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<DateTime?>("Contactdate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("Violation_p2.Models.Payment", b =>
                {
                    b.Property<int>("PaymentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PaymentId"));

                    b.Property<decimal?>("Paymentamount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<DateTime?>("Paymentdate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Paymentmethod")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<int?>("ViolationId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("PaymentId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("ViolationId");

                    b.ToTable("Payments");
                });

            modelBuilder.Entity("Violation_p2.Models.Role", b =>
                {
                    b.Property<int>("RoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RoleId"));

                    b.Property<string>("RoleCategory")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Rolename")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("RoleId");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Violation_p2.Models.Slider", b =>
                {
                    b.Property<int>("SliderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SliderId"));

                    b.Property<string>("Caption1")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Caption2")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Caption3")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Imagepath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Imagepath1")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("SliderId");

                    b.ToTable("Sliders");
                });

            modelBuilder.Entity("Violation_p2.Models.Testimonial", b =>
                {
                    b.Property<int>("TestimonialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestimonialId"));

                    b.Property<string>("Content")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<bool>("Isapproved")
                        .HasColumnType("NUMBER(1)");

                    b.Property<string>("Subject")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int>("UserId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("TestimonialId");

                    b.HasIndex("UserId");

                    b.ToTable("Testimonials");
                });

            modelBuilder.Entity("Violation_p2.Models.User1", b =>
                {
                    b.Property<int>("User1Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("User1Id"));

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Imagepath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Password")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("RoleId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<string>("Username")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("User1Id");

                    b.HasIndex("RoleId");

                    b.ToTable("User1s");
                });

            modelBuilder.Entity("Violation_p2.Models.Vehicle", b =>
                {
                    b.Property<int>("VehicleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("VehicleId"));

                    b.Property<string>("Color")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Imagepath")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<DateTime?>("Licenseexpirydate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<string>("Licenseplate")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Model")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Type")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<int?>("User1Id")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("VehicleId");

                    b.HasIndex("User1Id");

                    b.ToTable("Vehicles");
                });

            modelBuilder.Entity("Violation_p2.Models.Violation", b =>
                {
                    b.Property<int>("ViolationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViolationId"));

                    b.Property<decimal?>("Fineamount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<bool>("Ispaid")
                        .HasColumnType("NUMBER(1)");

                    b.Property<int?>("VehicleId")
                        .HasColumnType("NUMBER(10)");

                    b.Property<DateTime?>("Violationdate")
                        .HasColumnType("TIMESTAMP(7)");

                    b.Property<int?>("ViolationtypeId")
                        .HasColumnType("NUMBER(10)");

                    b.HasKey("ViolationId");

                    b.HasIndex("VehicleId");

                    b.HasIndex("ViolationtypeId");

                    b.ToTable("Violations");
                });

            modelBuilder.Entity("Violation_p2.Models.Violationtype", b =>
                {
                    b.Property<int>("ViolationtypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(10)");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ViolationtypeId"));

                    b.Property<decimal?>("Basefineamount")
                        .HasColumnType("DECIMAL(18, 2)");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("ViolationtypeId");

                    b.ToTable("Violationtypes");
                });

            modelBuilder.Entity("Violation_p2.Models.Blog", b =>
                {
                    b.HasOne("Violation_p2.Models.User1", "User")
                        .WithMany("Blogs")
                        .HasForeignKey("Userid");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Violation_p2.Models.Payment", b =>
                {
                    b.HasOne("Violation_p2.Models.Vehicle", "Vehicle")
                        .WithMany()
                        .HasForeignKey("VehicleId");

                    b.HasOne("Violation_p2.Models.Violation", "Violation")
                        .WithMany("Payments")
                        .HasForeignKey("ViolationId");

                    b.Navigation("Vehicle");

                    b.Navigation("Violation");
                });

            modelBuilder.Entity("Violation_p2.Models.Testimonial", b =>
                {
                    b.HasOne("Violation_p2.Models.User1", "User")
                        .WithMany("Testimonials")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("User");
                });

            modelBuilder.Entity("Violation_p2.Models.User1", b =>
                {
                    b.HasOne("Violation_p2.Models.Role", "Role")
                        .WithMany("User1s")
                        .HasForeignKey("RoleId");

                    b.Navigation("Role");
                });

            modelBuilder.Entity("Violation_p2.Models.Vehicle", b =>
                {
                    b.HasOne("Violation_p2.Models.User1", "User")
                        .WithMany("Vehicles")
                        .HasForeignKey("User1Id");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Violation_p2.Models.Violation", b =>
                {
                    b.HasOne("Violation_p2.Models.Vehicle", "Vehicle")
                        .WithMany("Violations")
                        .HasForeignKey("VehicleId");

                    b.HasOne("Violation_p2.Models.Violationtype", "Violationtype")
                        .WithMany("Violations")
                        .HasForeignKey("ViolationtypeId");

                    b.Navigation("Vehicle");

                    b.Navigation("Violationtype");
                });

            modelBuilder.Entity("Violation_p2.Models.Role", b =>
                {
                    b.Navigation("User1s");
                });

            modelBuilder.Entity("Violation_p2.Models.User1", b =>
                {
                    b.Navigation("Blogs");

                    b.Navigation("Testimonials");

                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("Violation_p2.Models.Vehicle", b =>
                {
                    b.Navigation("Violations");
                });

            modelBuilder.Entity("Violation_p2.Models.Violation", b =>
                {
                    b.Navigation("Payments");
                });

            modelBuilder.Entity("Violation_p2.Models.Violationtype", b =>
                {
                    b.Navigation("Violations");
                });
#pragma warning restore 612, 618
        }
    }
}
